### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by abb1991** [VashK/prj-rev-bwfs-dasmoto#2]
Your CSS looks great! I like your use of classes. When would you want to use an ID rather than a class?

**Comment by VashK** [comment]
Thank you. Okay, right. So I think I should have used ID attributes instead of classes for each h3 tag and my header div because the styles applied in this case would not be applied across multiple tags. They would be unique and targeted to just the tags where they are used. I should use classes when I want more broadly applicable styles to apply to multiple sections and tags within the html.
